### ISSUE TITLE
نصب آسان

### ISSUE THREAD

**Issue by erfjab** [Hiddify-Return/Hiddify-Manager-Bot#2]
سلام وقت بخیر 
بات زیرساخت خوبی داره و باید توسعه داده بشه، فقط بهتره یک فایل نصبی بنویسید که دوستان با یه دستور ساده بتونن نصب و استفاده کنن.

**Comment by Hiddify-Return** [comment]
> سلام وقت بخیر بات زیرساخت خوبی داره و باید توسعه داده بشه، فقط بهتره یک فایل نصبی بنویسید که دوستان با یه دستور ساده بتونن نصب و استفاده کنن.

سلام وقتت بخیر.
در برنامه توسعه دارمش اما خب چون فعلا روی ورژن یک هستیم یکم صبر کردم.
برای نصب آسان هم پیشنهاد خوبیه بیکارتر شدم یه bash براش مینویسم حتما
ممنون
